export const ORIGIN = "https://beyond-fluency-lab.vercel.app";
export const BUSINESS = 'Beyond Fluency Lab is an independent communication-coaching brand for people who already work and speak in English. From Learn With Smile, it offers live online coaching in public speaking, interviews and professional communication in groups of approximately 6, with course fees from €50 to €150.';
export const FOOTER_BLURB = 'Communication and interview coaching for university students, graduates and professionals who already speak English. From Learn With Smile: live online practice in groups of about six.';
export const AFFILIATION_Q = 'Are you affiliated with my university?';
export const AFFILIATION_A = "No. Beyond Fluency Lab is an independent programme — we are not partnered with, endorsed by, or officially connected to any specific university. If we ever do form a real partnership with a school, we'll state it clearly on this page, by name.";
export function pageMeta(path: string, title: string, description: string, _kind?: string) {
  return { path, title: title + " | Beyond Fluency Lab", description };
}
export const courses = [
 {slug:'speak-with-confidence',name:'Speak with Confidence',duration:'3–4 weeks',price:50,kicker:'01 / FIND YOUR FOOTING',headline:'Keep your voice. Even when the room gets louder.',description:'Live speaking and communication-confidence coaching in English for fluent speakers who hesitate, overthink or go quiet when it matters. A focused 3–4 week course for €50.',short:'Close the gap between what you know and what you can communicate in the moment.',dimension:'Pressure performance',for:'You can explain yourself in a relaxed conversation, but a meeting, presentation or unfamiliar group changes everything.',outcomes:['Enter a conversation without rehearsing every sentence.','Recover after a lost word or an interruption.','Deliver a clear, one-minute point with a calm ending.'],modules:[['Find your starting point','Bring a real speaking situation. Notice where hesitation begins and choose a practical response.'],['Practise the recovery','Rehearse pausing, restarting and asking for thinking time with a small live group.'],['Make it repeatable','Repeat your opening under gentle time pressure, with specific trainer feedback.']],segments:[0,1,2,3]},
 {slug:'career-interview-intensive',name:'Career & Interview Intensive',duration:'1 month',price:50,kicker:'02 / MAKE YOUR EXPERIENCE COUNT',headline:'Your experience deserves a better answer.',description:'Live interview communication coaching in English for graduates and career movers. Practise evidence-led answers and follow-up questions in one month for €50.',short:'Turn your experience into answers that are specific, credible and memorable.',dimension:'Structure + pressure',for:'You know your experience is relevant, but your answers become long, vague or overly rehearsed in interviews.',outcomes:['Build concise answers around an action and its evidence.','Respond to unexpected follow-up questions.','Explain your contribution without exaggerating it.'],modules:[['Choose the evidence','Map three experiences to the skills a role actually asks for.'],['Shape the answer','Practise a direct answer, supporting example and relevant takeaway.'],['Face the follow-up','Rehearse probing questions with your trainer and adapt without memorising a script.']],segments:[0,1,2,3]},
 {slug:'professional-communication',name:'Professional Communication',duration:'2 months',price:100,kicker:'03 / THE CORE PROGRAMME',headline:'Be understood. Then move the conversation forward.',description:'Live professional communication coaching in English for meetings, presentations, pitches and client conversations. Train persuasion, pressure and register over 2 months for €100.',short:'Build the complete second layer: structure, composure and the right register.',dimension:'All three dimensions',for:'You already work comfortably in English. You want people to understand your recommendation, trust your judgment and know what should happen next.',outcomes:['Make a recommendation with a reason and a clear next step.','Handle pushback without losing the thread.','Adapt your tone for colleagues, clients and decision-makers.'],modules:[['Persuasive structure','Lead with the decision. Select the evidence. End with a useful ask.'],['Pressure performance','Practise interrupted updates, difficult questions and live objections.'],['Register control','Say the same thing to a peer, client and senior stakeholder without changing its meaning.']],segments:[0,1,2,3]},
 {slug:'executive-communication',name:'Executive Communication',duration:'3 months',price:150,kicker:'04 / LEAD THE ROOM',headline:'Say less. Carry more weight.',description:'Executive communication coaching in English for public speaking, high-stakes decisions, negotiation and leadership. Small live groups and the same trainer for 3 months, €150.',short:'Develop judgment, authority and precision in high-stakes conversations.',dimension:'Advanced register + pressure',for:'Your conversations carry consequences: a difficult decision, a negotiation, a strategic pitch or a message people may challenge.',outcomes:['Frame a decision under ambiguity.','Disagree firmly while preserving a working relationship.','Lead a difficult conversation with precision and restraint.'],modules:[['Frame the stakes','State the choice, trade-offs and your recommendation with enough context to decide.'],['Hold the conversation','Practise resistance, negotiation and difficult questions without overexplaining.'],['Lead with range','Adjust directness, detail and tone across high-stakes stakeholder scenarios.']],segments:[0,1,2,3]}
];
export const segments = [
 {slug:'corporate-professionals',name:'Corporate Professionals',hook:'The overlooked promotion.',image:'corporate',course:2,pain:'You did the work. Someone else made the case.',intro:'Your English gets you through meetings. But your updates describe activity when the room needs a recommendation. The next step is making your judgment visible.',situations:['The update that disappears into the minutes.','The proposal you soften until it sounds optional.','The question that makes you abandon your strongest point.'],practice:'Take a routine project update. Start with the decision required, give one piece of evidence, then name the next action. Rehearse it again with an interruption.',guide:'make-your-work-visible'},
 {slug:'small-business-owners',name:'Small Business & SME Owners',hook:'The sale your English almost lost.',image:'sme',course:2,pain:'Your offer is strong. Your explanation wanders.',intro:'You know your business inside out. A buyer needs the part that matters to them: the problem, the value and a credible next step. Fluency alone does not make that selection for you.',situations:['The prospect who likes the idea but never decides.','The price objection you answer with an apology.','The follow-up that sounds either too formal or too familiar.'],practice:'Explain your offer in three sentences: the buyer’s problem, the change you can deliver and the next step you recommend. Have a partner challenge the value.',guide:'explain-your-value'},
 {slug:'sales-marketing',name:'Sales & Marketing',hook:'Comfortable talking, untrained at closing.',image:'sales',course:2,pain:'The conversation flows. The decision doesn’t.',intro:'You can keep a conversation going. Now train the moments that move it forward: a sharper question, a relevant answer to an objection and a next step both sides understand.',situations:['The objection you answer before understanding it.','The product story with no buyer-specific consequence.','The close that turns into “let me know what you think”.'],practice:'When a prospect says “too expensive”, ask what they are comparing it with. Summarise their concern before proposing a next step. Practise staying curious under pressure.',guide:'from-conversation-to-decision'},
 {slug:'graduating-students',name:'Graduating Students',hook:'The exam you never had.',image:'student',course:1,pain:'You passed English. Nobody tested your interview.',intro:'Exams reward a correct answer. Interviews ask you to choose a relevant example, explain your part and respond when the next question changes direction. That is a different kind of practice.',situations:['The “tell me about yourself” answer with no direction.','The group task where your idea arrives too late.','The follow-up question your rehearsed answer cannot cover.'],practice:'Choose one real project. Say what needed to happen, what you personally did and what changed. Ask a friend to interrupt with “why?” and answer without starting again.',guide:'the-interview-after-the-exam'}
];
export const faqs = [
 ['Is this an English course for beginners?','No. The programme is designed for people who already communicate in English. We train the second layer: persuasive structure, pressure performance and register control. The free trial helps establish whether the level is right for you.'],
 ['How are the live sessions organised?','You learn online in a small batch of approximately 6, with the same trainer throughout your course. Cohort dates, session frequency, session length and the time in your local time zone are confirmed before enrolment.'],
 ['What does each course cost?','Speak with Confidence costs €50 for 3–4 weeks. Career & Interview Intensive costs €50 for 1 month. Professional Communication costs €100 for 2 months. Executive Communication costs €150 for 3 months. These are one-time course fees excluding VAT, not monthly subscriptions.'],
 ['Do I need to take the courses in order?','No. The tiers describe increasing scope, not compulsory prerequisites. Choose a focused course for an immediate situation or Professional Communication for all three dimensions. Your trainer can discuss fit during the trial.'],
 ['What happens after the course?','Alumni are invited to a monthly live practice session so the work continues beyond the course. Session dates and access details are shared with the cohort.'],
 ['Will this guarantee a promotion, job or sale?','No. Coaching gives you deliberate practice and feedback. Results depend on your context, attendance and practice; we do not guarantee employment, promotions, revenue or a particular outcome.'],
 ['Are there testimonials from Europe?','Not yet. Beyond Fluency Lab has just launched its founding European cohort. The Parent-academy stories on our testimonials page belong to Learn With Smile’s existing programmes.'],
 [AFFILIATION_Q,AFFILIATION_A]
];
