import type { ReactNode } from "react";
import { PageHero } from "./site-pages";

type PolicyKind = "terms" | "privacy" | "cookies" | "refunds";
const meta: Record<PolicyKind, { title: string; summary: string; sections: string[] }> = {
  terms: { title: "Terms & Conditions", summary: "The practical terms for using this website and joining a Beyond Fluency Lab programme.", sections: ["Provider", "Programmes", "Booking", "Payments", "Participation", "Intellectual property", "Liability", "Changes", "Contact"] },
  privacy: { title: "Privacy Policy", summary: "What information we collect, why we use it and the choices available to you.", sections: ["Controller", "Information", "Purposes", "Sharing", "Transfers", "Retention", "Your rights", "Security", "Contact"] },
  cookies: { title: "Cookie Policy", summary: "A straightforward explanation of cookies and browser storage used by this website.", sections: ["Current use", "Essential storage", "Diagnostic", "Campaign links", "Your controls", "Changes", "Contact"] },
  refunds: { title: "Cancellation & Refund Policy", summary: "How cancellations, rescheduling, withdrawals and refunds are handled.", sections: ["Free trial", "Before payment", "Cooling-off period", "Learner cancellation", "Rescheduling", "Provider cancellation", "Refunds", "Contact"] },
};
const id = (value: string) => value.toLowerCase().replaceAll(" ", "-");
function Section({ title, children }: { title: string; children: ReactNode }) { return <section id={id(title)}><h2>{title}</h2>{children}</section>; }
function PolicyNav({ kind }: { kind: PolicyKind }) { const links: [PolicyKind, string][] = [["terms", "Terms & Conditions"], ["privacy", "Privacy Policy"], ["cookies", "Cookie Policy"], ["refunds", "Cancellation & Refunds"]]; return <aside className="policy-nav" aria-label="Policy contents"><p className="eyebrow">ON THIS PAGE</p><ol>{meta[kind].sections.map((section) => <li key={section}><a href={`#${id(section)}`}>{section}</a></li>)}</ol><div className="policy-links">{links.filter(([key]) => key !== kind).map(([key, label]) => <a key={key} href={`/legal/${key}`}>{label}</a>)}</div></aside>; }

function Terms() { return <>
  <Section title="Provider"><p>Beyond Fluency Lab is a communication-coaching programme from Learn With Smile. References to “we”, “us” and “our” mean the business operating Beyond Fluency Lab. Contact the team through the <a href="/contact">contact page</a>.</p></Section>
  <Section title="Programmes"><p>We provide live online communication coaching for adults who already use English. Programme descriptions, duration and listed fees appear on the relevant course page. Coaching is educational and developmental; it is not a regulated qualification, therapy, legal advice or employment service.</p><p>Examples, exercises and diagnostic results are guidance only. We do not guarantee a job, promotion, sale, examination result or particular outcome.</p></Section>
  <Section title="Booking"><p>A trial or enrolment form is a request, not an automatic booking. A place is confirmed only after we agree the programme, cohort dates, session schedule, complete price and applicable taxes with you in writing. You must be at least 18 and provide accurate information.</p></Section>
  <Section title="Payments"><p>Fees are shown in euros and exclude VAT. The payable amount is confirmed before payment. Payments may be processed securely by Stripe and supported card networks. We do not store full card numbers.</p><p>See our <a href="/legal/refunds">Cancellation & Refund Policy</a>.</p></Section>
  <Section title="Participation"><p>Join on time, participate respectfully and use suitable equipment and connectivity. Do not share confidential employer, client or personal information. You may not record or distribute a session without prior permission from everyone identifiable in it.</p></Section>
  <Section title="Intellectual property"><p>The website, course structure, exercises, materials, graphics and brand assets belong to Beyond Fluency Lab, Learn With Smile or their licensors. Enrolment gives you personal, non-transferable use of supplied materials; it does not permit resale or publication.</p></Section>
  <Section title="Liability"><p>We provide the website and coaching with reasonable care and skill. We are not responsible for events outside our reasonable control, third-party services, your connection or reliance on coaching as professional advice. Nothing excludes liability or consumer rights that cannot lawfully be excluded.</p></Section>
  <Section title="Changes"><p>We may improve the website, programmes or these terms. Material changes will appear here with a new effective date. Terms agreed for an existing paid booking continue unless a change is required by law or agreed with you.</p></Section>
  <Section title="Contact"><p>Send questions or complaints through the <a href="/contact">contact page</a>. We aim to acknowledge substantive complaints promptly and resolve them fairly.</p></Section>
</>; }

function Privacy() { return <>
  <Section title="Controller"><p>The business operating Beyond Fluency Lab is responsible for personal information collected through this website. Submit privacy questions through the <a href="/contact">contact page</a>.</p></Section>
  <Section title="Information"><p>When you request a trial, course place or report, we may collect your name, email, time zone, availability, selected programme, communication goal and message. The diagnostic calculates a suggested focus; unless you submit a form, answers remain in your browser. Hosting providers may receive basic technical and security information such as IP address, browser type, request time and error logs.</p></Section>
  <Section title="Purposes"><p>We use information to answer enquiries, arrange trials and cohorts, provide courses, deliver requested reports, process payments, maintain security, meet legal obligations and resolve complaints. The legal basis may be pre-contract steps, performance of a contract, legal obligations, consent or legitimate interests. We do not sell personal information or add trial requests to unrelated marketing lists.</p></Section>
  <Section title="Sharing"><p>Information is shared only where needed with providers supporting hosting, forms, databases, email, scheduling, video delivery and payments. Stripe and card networks receive payment information when you pay. We may also disclose information where required by law or necessary to protect people and the service.</p></Section>
  <Section title="Transfers"><p>Some providers may process information outside your country or the European Economic Area. Where required, recognised safeguards such as adequacy decisions or contractual protections are used.</p></Section>
  <Section title="Retention"><p>We keep information only as long as needed for course delivery, reasonable follow-up, accounting, dispute resolution and legal obligations. Enquiries are periodically reviewed and deleted or anonymised when no longer required.</p></Section>
  <Section title="Your rights"><p>Depending on applicable law, you may request access, correction, deletion, restriction or portability, object to certain processing or withdraw consent. You may complain to your local data-protection authority. Identity verification may be required. The diagnostic does not make a legally significant decision about you.</p></Section>
  <Section title="Security"><p>We use proportionate safeguards including secure connections, input validation, access controls and restricted administration. No online system can guarantee absolute security.</p></Section>
  <Section title="Contact"><p>Use the <a href="/contact">contact page</a> and write “Privacy request” in your message.</p></Section>
</>; }

function Cookies() { return <>
  <Section title="Current use"><p>This website does not currently use advertising cookies or third-party marketing pixels, and does not use cookies to build advertising profiles.</p></Section>
  <Section title="Essential storage"><p>Hosting and security services may use strictly necessary cookies or similar storage to deliver pages, prevent abuse and maintain secure sessions. The motion control stores a device preference named <code>bfl-motion</code>.</p></Section>
  <Section title="Diagnostic"><p>Diagnostic answers remain in the open page’s memory and clear when the page refreshes. A shared result link contains only the named focus, not your email, answers or scores.</p></Section>
  <Section title="Campaign links"><p>Campaign parameters already present in a link may be preserved between pages and attached to a form you submit. This does not place a separate advertising cookie.</p></Section>
  <Section title="Your controls"><p>You can inspect, block or delete cookies and site storage in browser settings. Blocking essential storage may prevent some features from working. Because optional analytics and advertising cookies are not currently set, no consent banner is shown.</p></Section>
  <Section title="Changes"><p>If optional analytics, advertising or other non-essential storage is introduced, this policy and the consent controls will be updated before it is used where required.</p></Section>
  <Section title="Contact"><p>Send questions through the <a href="/contact">contact page</a>. See the <a href="/legal/privacy">Privacy Policy</a> for personal-data information.</p></Section>
</>; }

function Refunds() { return <>
  <Section title="Free trial"><p>A free-trial request does not require payment or commit you to buying a course. If a trial must move, we will agree another available time.</p></Section>
  <Section title="Before payment"><p>Before accepting payment, we confirm the programme, cohort dates, schedule, complete price, applicable taxes and cancellation terms. Check these details before paying.</p></Section>
  <Section title="Cooling-off period"><p>If consumer law gives you a cooling-off or withdrawal period for an online purchase, those rights continue to apply. If you ask us to begin coaching during that period, we may request legally required confirmation and may charge proportionately for services already supplied where permitted.</p></Section>
  <Section title="Learner cancellation"><p>Tell us promptly if you need to cancel. Any refund considers the cancellation date, sessions delivered and the booking terms confirmed before purchase. We never reduce mandatory consumer rights.</p></Section>
  <Section title="Rescheduling"><p>Rescheduling depends on the course format and cohort availability. A group session may not be repeatable because other learners’ schedules and privacy must be respected. We will explain available catch-up options fairly.</p></Section>
  <Section title="Provider cancellation"><p>If we cancel a paid programme and cannot offer a reasonable alternative, you may choose a refund for undelivered services. Temporary trainer unavailability may be handled with a replacement or rescheduled session.</p></Section>
  <Section title="Refunds"><p>Approved refunds return to the original payment method where possible. Banks and card networks control final posting time. We confirm the amount and submission in writing.</p></Section>
  <Section title="Contact"><p>Use the <a href="/contact">contact page</a> with the booking email, programme and cohort date.</p></Section>
</>; }

export function LegalPage({ kind }: { kind: PolicyKind }) { const policy = meta[kind]; return <main id="main"><PageHero eyebrow="LEGAL" title={policy.title} description={policy.summary}/><section className="wrap section policy-layout"><PolicyNav kind={kind}/><article className="policy-copy prose"><div className="policy-meta"><span>Effective 8 September 2026</span><span>Plain-language policy</span></div>{kind === "terms" ? <Terms/> : kind === "privacy" ? <Privacy/> : kind === "cookies" ? <Cookies/> : <Refunds/>}<div className="policy-review"><strong>Important</strong><p>This practical baseline should be reviewed for the final operating entity, location, tax position and delivery process before paid enrolment opens.</p></div></article></section></main>; }
