/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as EnrolRouteImport } from './routes/enrol'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OurMethodRouteImport } from './routes/our-method'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as WhoItsForIndexRouteImport } from './routes/who-its-for.index'
import { Route as WhoItsForSlugRouteImport } from './routes/who-its-for.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrolRoute = EnrolRouteImport.update({
  id: '/enrol',
  path: '/enrol',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OurMethodRoute = OurMethodRouteImport.update({
  id: '/our-method',
  path: '/our-method',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoItsForIndexRoute = WhoItsForIndexRouteImport.update({
  id: '/who-its-for/',
  path: '/who-its-for/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoItsForSlugRoute = WhoItsForSlugRouteImport.update({
  id: '/who-its-for/$slug',
  path: '/who-its-for/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/diagnostic': typeof DiagnosticRoute
  '/enrol': typeof EnrolRoute
  '/faq': typeof FaqRoute
  '/our-method': typeof OurMethodRoute
  '/pricing': typeof PricingRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/who-its-for/$slug': typeof WhoItsForSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/who-its-for/': typeof WhoItsForIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/diagnostic': typeof DiagnosticRoute
  '/enrol': typeof EnrolRoute
  '/faq': typeof FaqRoute
  '/our-method': typeof OurMethodRoute
  '/pricing': typeof PricingRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/who-its-for/$slug': typeof WhoItsForSlugRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/who-its-for': typeof WhoItsForIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/diagnostic': typeof DiagnosticRoute
  '/enrol': typeof EnrolRoute
  '/faq': typeof FaqRoute
  '/our-method': typeof OurMethodRoute
  '/pricing': typeof PricingRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/who-its-for/$slug': typeof WhoItsForSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/who-its-for/': typeof WhoItsForIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/brand-kit'
    | '/contact'
    | '/diagnostic'
    | '/enrol'
    | '/faq'
    | '/our-method'
    | '/pricing'
    | '/testimonials'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/who-its-for/$slug'
    | '/blog/'
    | '/courses/'
    | '/who-its-for/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/brand-kit'
    | '/contact'
    | '/diagnostic'
    | '/enrol'
    | '/faq'
    | '/our-method'
    | '/pricing'
    | '/testimonials'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/who-its-for/$slug'
    | '/blog'
    | '/courses'
    | '/who-its-for'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/brand-kit'
    | '/contact'
    | '/diagnostic'
    | '/enrol'
    | '/faq'
    | '/our-method'
    | '/pricing'
    | '/testimonials'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/who-its-for/$slug'
    | '/blog/'
    | '/courses/'
    | '/who-its-for/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BrandKitRoute: typeof BrandKitRoute
  ContactRoute: typeof ContactRoute
  DiagnosticRoute: typeof DiagnosticRoute
  EnrolRoute: typeof EnrolRoute
  FaqRoute: typeof FaqRoute
  OurMethodRoute: typeof OurMethodRoute
  PricingRoute: typeof PricingRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  WhoItsForSlugRoute: typeof WhoItsForSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  WhoItsForIndexRoute: typeof WhoItsForIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrol': {
      id: '/enrol'
      path: '/enrol'
      fullPath: '/enrol'
      preLoaderRoute: typeof EnrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-method': {
      id: '/our-method'
      path: '/our-method'
      fullPath: '/our-method'
      preLoaderRoute: typeof OurMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-its-for/': {
      id: '/who-its-for/'
      path: '/who-its-for'
      fullPath: '/who-its-for/'
      preLoaderRoute: typeof WhoItsForIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-its-for/$slug': {
      id: '/who-its-for/$slug'
      path: '/who-its-for/$slug'
      fullPath: '/who-its-for/$slug'
      preLoaderRoute: typeof WhoItsForSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BrandKitRoute: BrandKitRoute,
  ContactRoute: ContactRoute,
  DiagnosticRoute: DiagnosticRoute,
  EnrolRoute: EnrolRoute,
  FaqRoute: FaqRoute,
  OurMethodRoute: OurMethodRoute,
  PricingRoute: PricingRoute,
  TestimonialsRoute: TestimonialsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  WhoItsForSlugRoute: WhoItsForSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  WhoItsForIndexRoute: WhoItsForIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
